services:
  api:
    build:
      context: ./api/.
      dockerfile: Dockerfile
    ports:
      - "9000:8080"
    restart: always
    container_name: "api_container"
    environment:
      MONGODB_URI: mongo:27017
  public:
    build:
      context: ./public/.
      dockerfile: Dockerfile
    ports:
      - "9001:3000"
    restart: always
    container_name: "public_container"
  mongo:
    image: mongo
    restart: always
    command: mongod --quiet --logpath /dev/null
    ports:
      - 9100:27017
    container_name: "mongo_container"

